config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures
  resources :courses
  get 'welcome/index'
  devise_for :users

  root 'welcome#index'

  resources :lectures do 
    resources :comments
  member do
    put "like", to: "lectures#upvote"
    put "dislike", to: "lectures#downvote"
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :lecture
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many :lectures

  validates :title, presence: true
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
 belongs_to :course
 belongs_to :user

 has_many :comments , dependent: :destroy

 mount_uploader :attachment, AttachmentUploader
 validates :content, presence: true
 acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  	
  	has_many :courses
	has_many :lectures
	has_many :comments, dependent: :destroy

	validates :name, uniqueness: true, presence: true, length: { minimum: 3 }
	validates :email, uniqueness: true
	validates :password,confirmation: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	
	Gender_Types = ["Male", "Female"]
	
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:gender,:dob,:image,:remove_image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_lecture
	before_action :find_comment,only: [:destroy, :edit, :update, :comment_owner]
	before_action :comment_owner,only: [:edit, :update, :destroy]

	def index
    	@comments = Comment.all
  	end

	def create
		@comment = @lecture.comments.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.save

		if @comment.save
			redirect_to lecture_path(@lecture)
		else
			render 'new'
		end
	end

	def destroy
		@comment.destroy
		redirect_to lecture_path(@lecture)
	end

	def edit
	
	end

	def update
		if @comment.update(params[:comment].permit(:content))
		redirect_to lecture_path(@lecture)
		else
		render 'edit'
		end	
	end

	private
		def find_lecture
			@lecture = Lecture.find(params[:lecture_id])
		end

		def find_comment
			@comment = @lecture.comments.find(params[:id])
		end 

		def comment_owner
			unless current_user.id == @comment.user_id
			flash[:notice] = "You Don't Have Access to other people comments"
			redirect_to @lecture
			end
		end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user_id = current_user.id
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :user_id)
    end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]
  before_action :load_courses,only: [:create,:new,:edit,:update]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
    @comments=Comment.where(lecture_id: @lecture).order("created_at ASC")
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.user_id = current_user.id
    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def load_courses
    @courses=Course.where(user_id: current_user.try(:id))
  end

  def upvote 
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:content, :attachment, :course_id, :user_id)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<h3> This Post Has <%= pluralize(@comments.count, "Comment") %> </h3>

<% @comments.each do |comment| %>
<p><b><%= comment.user.name %></b></p>
<p><%= comment.content %><span>  <%= comment.created_at %></span></p>
<% if current_user == comment.user %>
<%= link_to "Delete Comment", [comment.lecture, comment], method: :delete %>
<%= link_to "Edit Comment", edit_lecture_comment_path(comment.lecture, comment) %>
<% end %>
<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for([@lecture,@lecture.comments.build]) do |f| %>

 <div class="form-group">
<%= f.text_area :content, class: "form-control" %>
<%= f.submit %>
</div>

<% end %>

app/views/comments/edit.html.erb
<%= form_for ([@lecture,@comment]) do |f| %>

<%= f.text_area :content %>
<%= f.submit %>

<% end %>

app/views/courses/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <center><h3 class="panel-title">Course</h3></center>
  </div>
  <div class="panel-body">

<%= form_for(@course) do |f| %>

  <% if @course.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>
      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
<% if current_user&&@course.user==current_user  %>
    <%= f.label :user_id %><br>
    <%= current_user.try(:name)  %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/courses/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><center>Available Course List</center></h3>
  </div>
  <p id="notice"><%= notice %></p>
  <div class="panel-body">
<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.try(:user).try(:name) %></td>
        <td><%= link_to 'Show', course %></td>
        <% if course.user == current_user %>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<p><center><%= link_to 'New Course', new_course_path, class: "btn btn-primary" %></center></p>
</div>

app/views/courses/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<% if notice %>
<div class="alert alert-info" role="alert">
<p id="notice"><%= notice %></p>
</div>
<% end %>

<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      <th>User</th>
      <th>Title</th>
    </tr>
  </thead>
 <tbody>
 <tr><td><%= @course.try(:user).try(:name) %></td>
<td><%= @course.title %></td>
</tr>
 </tbody>
</table>
<% if @course.user==current_user  %>
<%= link_to 'Edit', edit_course_path(@course) %> |
<% end %>
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mooc</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Welcome <%= current_user.try(:name) %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
       <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
       <li><%= link_to 'Check Available Courses', courses_path %></li>
       <li><%= link_to 'Check Available Lectures', lectures_path %></li>
          </ul>
        </li>
      </ul>



      <ul class="nav navbar-nav navbar-right">
      <% if current_user.present? %>
       <li><%= link_to "Log out", destroy_user_session_path, :method => "delete" %></li>
       <% else %>       
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/lectures/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <center><h3 class="panel-title">Lecture</h3></center>
  </div>
  <div class="panel-body">

<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.cktext_area :content , class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
  <div class="form-group">
    <%= f.label :course_id %><br>
    <%= f.collection_select :course_id,@courses, :id, :title %>
  </div>
  <div class="form-group">
<% if current_user && @lecture.user==current_user  %>
    <%= f.label :user_id %><br>
    <%= current_user.try(:name)  %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/lectures/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><center>Available Lectures List</center></h3>
  </div>
  <p id="notice"><%= notice %></p>
  <div class="panel-body">
<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Attachment</th>
      <th>Course</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.try(:user).try(:name) %></td>
        <td><%= raw lecture.content %></td>
        <% if lecture.attachment_url %>
        <td><%= link_to "Download", lecture.attachment_url %></td>
        <% else %>
        <td>No Link</td>
        <% end %>
        <td><%= lecture.try(:course).try(:title) %></td>
        <td><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"><%= link_to like_lecture_path(lecture), method: :put do %>
         Upvote
        <%= lecture.get_upvotes.size %>
        <% end %></span></td>
        <td><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"><%= link_to dislike_lecture_path(lecture), method: :put do %>
        Spam
        <%= lecture.get_downvotes.size %>
        <% end %></span>
        </td>
        <td><%= link_to 'Show', lecture %></td>
       <% if lecture.user == current_user %>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<p><center><%= link_to 'New Lecture', new_lecture_path, class: "btn btn-primary" %></center></p>
</div>
</div>

app/views/lectures/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<% if notice %>
<div class="alert alert-info" role="alert">
<p id="notice"><%= notice %></p>
</div>
<% end %>

  <div class="form-group">
  <span><strong>Content</strong></span>
  <span class="form-control" ><%= raw@lecture.content %></span>
</div>

  <div class="form-group">
  <span><strong>Attachment</strong></span>
  <span class="form-control" ><%= @lecture.try(:attachment) %></span>
</div>

  <div class="form-group">
  <span><strong>Course</strong></span>
  <span class="form-control" ><%= @lecture.try(:course).try(:title) %></span>
</div>

  <div class="form-group">
  <span><strong>User</strong></span>
  <span class="form-control" ><%= @lecture.try(:user).try(:name) %></span>
</div>
<hr>
<%= render 'comments/comment' %>

<% if @lecture.user==current_user  %>
<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<% end %>
<%= link_to 'Back', lectures_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="jumbotron">
<center>
  <h1>Welcome to Online Mooc</h1>
  <p>A massive open online course is an online course aimed at unlimited participation and open access via the web.In addition to traditional course materials such as filmed lectures, readings, and problem sets</p>
  <% if current_user.present? %>
  <p><%= link_to "Log out", destroy_user_session_path, :method => "delete", class: "btn btn-danger btn-lg" %></p>
  <% else %>  
  <p><%= link_to "Log-In", new_user_session_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  <% end %>
</center>
</div>